#include "common.h"

#define VS_TRAIL_ORIGIN_FUNCTION func_800F98E0
#define VS_TRAIL_TARGET_FUNCTION func_800FA07C
#define VS_TRAIL_CONTROL_FUNCTION func_800FA294
#define VS_TRAIL_INIT_FUNCTION func_800FA758
#define VS_TRAIL_UPDATE_FUNCTION func_800FA8D0
#define VS_TRAIL_RENDER_FUNCTION func_800FAA5C
#define VS_TRAIL_DISPATCH_FUNCTION func_800FB4B8
#define VS_TRAIL_CORNER_STATE D_800FC8F8
#include "src/EFFECT/trails5.h"

#define VS_TILED_RING_FUNCTION func_800FBA00
#define VS_TILED_RING_COLORS D_800FC8FC
#include "src/EFFECT/tiledRings.h"
