sha1: 8c878b5fd42badad937726f1fc1f1382cd60e07c
options:
  basename: EFFECT/PLG297.BIN
  target_path: data/EFFECT/PLG297.BIN
  elf_path: build/data/EFFECT/PLG297.BIN.elf
  asm_path: build/src/EFFECT/PLG297.BIN
  src_path: src/EFFECT/PLG297.BIN
  asset_path: build/assets/EFFECT/PLG297.BIN
  ld_script_path: build/config/EFFECT/PLG297.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG297.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG297.BIN/undefined_syms_auto.txt


segments:
  - name: PLG297.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 18]
    - [0x18, c]
    - [0x3370, data, 18]
  - [0x3630]
