sha1: 07b9d2b37b418f89032111b6e00745f9bd20d0d2
options:
  basename: EFFECT/PLG138.BIN
  target_path: data/EFFECT/PLG138.BIN
  elf_path: build/data/EFFECT/PLG138.BIN.elf
  asm_path: build/src/EFFECT/PLG138.BIN
  src_path: src/EFFECT/PLG138.BIN
  asset_path: build/assets/EFFECT/PLG138.BIN
  ld_script_path: build/config/EFFECT/PLG138.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG138.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG138.BIN/undefined_syms_auto.txt


segments:
  - name: PLG138.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 18]
    - [0x18, c]
    - [0x353C, data, 18]
  - [0x357C]
