#include "common.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800F98F8
#define VS_PARTICLE_TARGET_FUNCTION func_800FA080
#define VS_PARTICLE_CONTROL_FUNCTION func_800FA298
#define VS_PARTICLE_RENDER_FUNCTION func_800FA748
#define VS_PARTICLE_CORNER_STATE D_800FAEEC
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

#define VS_PARTICLE_RENDER_FUNCTION func_800FA748
#include "src/EFFECT/particleLineRender.h"
#undef VS_PARTICLE_RENDER_FUNCTION

#define VS_PARTICLE_ORIGIN_FUNCTION func_800F98F8
#define VS_PARTICLE_TARGET_FUNCTION func_800FA080
#define VS_PARTICLE_CONTROL_FUNCTION func_800FA298
#define VS_PARTICLE_RENDER_FUNCTION func_800FA748
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FAC78
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"
