sha1: 681eb329b1bbfa6e72774842bbbfc2f7c8ad8353
options:
  basename: EFFECT/PLG054.BIN
  target_path: data/EFFECT/PLG054.BIN
  elf_path: build/data/EFFECT/PLG054.BIN.elf
  asm_path: build/src/EFFECT/PLG054.BIN
  src_path: src/EFFECT/PLG054.BIN
  asset_path: build/assets/EFFECT/PLG054.BIN
  ld_script_path: build/config/EFFECT/PLG054.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG054.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG054.BIN/undefined_syms_auto.txt


segments:
  - name: PLG054.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 18]
    - [0x18, c]
    - [0x1AD4, data, 18]
  - [0x1AF4]
