#include "lbas.h"

int _illustLbas[] = { VS_ILLUST06_BIN_LBA, VS_ILLUST07_BIN_LBA, VS_ILLUST08_BIN_LBA,
    VS_ILLUST09_BIN_LBA, VS_ILLUST10_BIN_LBA, VS_ILLUST11_BIN_LBA, VS_ILLUST12_BIN_LBA,
    VS_ILLUST13_BIN_LBA, VS_ILLUST14_BIN_LBA, VS_ILLUST15_BIN_LBA, VS_ILLUST16_BIN_LBA, 0,
    0, 0, 0, 0 };

int _illustSizes[] = { VS_ILLUST06_BIN_SIZE, VS_ILLUST07_BIN_SIZE, VS_ILLUST08_BIN_SIZE,
    VS_ILLUST09_BIN_SIZE, VS_ILLUST10_BIN_SIZE, VS_ILLUST11_BIN_SIZE,
    VS_ILLUST12_BIN_SIZE, VS_ILLUST13_BIN_SIZE, VS_ILLUST14_BIN_SIZE,
    VS_ILLUST15_BIN_SIZE, VS_ILLUST16_BIN_SIZE, 0, 0, 0, 0, 0 };