sha1: 44a2e649370fff38cbc79ead975ba12e34c902f5
options:
  basename: EFFECT/PLG044.BIN
  target_path: data/EFFECT/PLG044.BIN
  elf_path: build/data/EFFECT/PLG044.BIN.elf
  asm_path: build/src/EFFECT/PLG044.BIN
  src_path: src/EFFECT/PLG044.BIN
  asset_path: build/assets/EFFECT/PLG044.BIN
  ld_script_path: build/config/EFFECT/PLG044.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG044.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG044.BIN/undefined_syms_auto.txt


segments:
  - name: PLG044.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0x0, c]
    - [0xEF8, data, 0]
  - [0xF18]
