sha1: f0e8773fe326f65f53be081c0d73fb232aa170f8
options:
  basename: MENU/MENU0.PRG
  target_path: data/MENU/MENU0.PRG
  elf_path: build/data/MENU/MENU0.PRG.elf
  asm_path: build/src/MENU/MENU0.PRG
  src_path: src/MENU/MENU0.PRG
  asset_path: build/assets/MENU/MENU0.PRG
  ld_script_path: build/config/MENU/MENU0.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENU0.PRG/symbol_addrs.txt
    - config/MENU/MENU0.PRG/exports.txt
    - config/MENU/MAINMENU.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
    - config/BATTLE/BATTLE.PRG/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENU0.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENU0.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 84]
      - [0x84, c]
      - { start: 0x2258, type: vsStringTable, name: base, linker_entry: false }
      - { start: 0x3594, type: vsStringTable, name: teleportation, linker_entry: false }
      - [0x40E8, bss, 84]
  - [0x4211]
