sha1: f0e8773fe326f65f53be081c0d73fb232aa170f8
options:
  basename: MENU/MENU0.PRG
  target_path: data/MENU/MENU0.PRG
  elf_path: build/data/MENU/MENU0.PRG.elf
  asm_path: build/src/MENU/MENU0.PRG
  src_path: src/MENU/MENU0.PRG
  asset_path: build/assets/MENU/MENU0.PRG
  ld_script_path: build/config/MENU/MENU0.PRG/link.ld
  create_undefined_funcs_auto: false
  create_undefined_syms_auto: false
  auto_link_sections: [.rodata, .data, .bss]

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 1
    subsegments:
      - [0x84, c]
      - [0x15AC, c]
      - { start: 0x2258, type: vsStringTable, name: magic, linker_entry: false }
      - { start: 0x3594, type: vsStringTable, name: teleportation, linker_entry: false }
  - [0x4211]
