sha1: 646d935653d8dfc27bce1bc3381aeb8b10cdbfda
options:
  basename: EFFECT/PLG069.BIN
  target_path: data/EFFECT/PLG069.BIN
  elf_path: build/data/EFFECT/PLG069.BIN.elf
  asm_path: build/src/EFFECT/PLG069.BIN
  src_path: src/EFFECT/PLG069.BIN
  asset_path: build/assets/EFFECT/PLG069.BIN
  ld_script_path: build/config/EFFECT/PLG069.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG069.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG069.BIN/undefined_syms_auto.txt


segments:
  - name: PLG069.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, E0]
    - [0xE0, c]
    - [0x3C04, data, E0]
  - [0x3CF8]
