sha1: b9d605e17e9063680eeb6e355ea7a734ddb40bb6
options:
  basename: MENU/MENU1.PRG
  target_path: data/MENU/MENU1.PRG
  elf_path: build/data/MENU/MENU1.PRG.elf
  asm_path: build/src/MENU/MENU1.PRG
  src_path: src/MENU/MENU1.PRG
  asset_path: build/assets/MENU/MENU1.PRG
  ld_script_path: build/config/MENU/MENU1.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENU1.PRG/symbol_addrs.txt
    - config/MENU/MENU1.PRG/exports.txt
    - config/MENU/MAINMENU.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENU1.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENU1.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 30]
      - [0x30, c]
      - [0xC78, data, 30]
      - [0x1D00, bss, 30]
  - [0x1D46]
