sha1: bb3420a69b617ed5fa31669ae2ba3a75c2094ca4
options:
  basename: EFFECT/PLG153.BIN
  target_path: data/EFFECT/PLG153.BIN
  elf_path: build/data/EFFECT/PLG153.BIN.elf
  asm_path: build/src/EFFECT/PLG153.BIN
  src_path: src/EFFECT/PLG153.BIN
  asset_path: build/assets/EFFECT/PLG153.BIN
  ld_script_path: build/config/EFFECT/PLG153.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG153.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG153.BIN/undefined_syms_auto.txt


segments:
  - name: PLG153.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 110]
    - [0x110, c]
    - [0x34E4, data, 110]
  - [0x35D8]
