sha1: 9d6a9ec13c00b4a45084a8d31ef867e924d8d0f1
options:
  basename: EFFECT/PLG250.BIN
  target_path: data/EFFECT/PLG250.BIN
  elf_path: build/data/EFFECT/PLG250.BIN.elf
  asm_path: build/src/EFFECT/PLG250.BIN
  src_path: src/EFFECT/PLG250.BIN
  asset_path: build/assets/EFFECT/PLG250.BIN
  ld_script_path: build/config/EFFECT/PLG250.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG250.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG250.BIN/undefined_syms_auto.txt


segments:
  - name: PLG250.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0x1E28, data, 0]
  - [0x1E48]
