sha1: c2e91aec2752468155c4a8a4406bc2282ec7cd52
options:
  basename: MENU/MENU7.PRG
  target_path: data/MENU/MENU7.PRG
  elf_path: build/data/MENU/MENU7.PRG.elf
  asm_path: build/src/MENU/MENU7.PRG
  src_path: src/MENU/MENU7.PRG
  asset_path: build/assets/MENU/MENU7.PRG
  ld_script_path: build/config/MENU/MENU7.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENU7.PRG/symbol_addrs.txt
    - config/MENU/MENU7.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
    - config/BATTLE/BATTLE.PRG/exports.txt
    - config/MENU/MAINMENU.PRG/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENU7.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENU7.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 2
    subsegments:
      - [0x0, .rodata, 260]
      - [0x260, c]
      - [0x7AB4, .data, 260]
      - [0x8240, .bss, 260]
  - [0x88AE]
