warlock:
warlockDesc:
warlockLocked:
shaman:
shamanDesc:
shamanLocked:
sorcerer:
sorcererDesc:
sorcererLocked:
enchanter:
enchanterDesc:
enchanterLocked:
warlockSpellDescs:
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
shamanSpellDescs:
-
-
-
-
-
-
sorcererSpellDescs:
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
enchanterSpellDescs:
-
-
-
-
-
-
-
-
warlockSpells:
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
