sha1: 55100b476a0398589a31b8ad8daf1ad8398ee2ba
options:
  basename: MENU/MENU2.PRG
  target_path: data/MENU/MENU2.PRG
  elf_path: build/data/MENU/MENU2.PRG.elf
  asm_path: build/src/MENU/MENU2.PRG
  src_path: src/MENU/MENU2.PRG
  asset_path: build/assets/MENU/MENU2.PRG
  ld_script_path: build/config/MENU/MENU2.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENU2.PRG/symbol_addrs.txt
    - config/MENU/MENU2.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
    - config/MENU/MAINMENU.PRG/exports.txt
    - config/BATTLE/BATTLE.PRG/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENU2.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENU2.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 64]
      - [0x2C, .rodata, 143C]
      - [0x64, c]
      - [0x143C, c]
      - { start: 0x1E90, type: vsStringTable, name: battleAbilities, linker_entry: false }
      - [0x26B4, .data, 64]
      - [0x26D8, .data, 143C]
      - [0x28B0, .bss, 64]
      - [0x28F0, .bss, 143C]
  - [0x2920]
