sha1: 0c4b43312922cb9e1e26d73fef7c4093e99e234e
options:
  basename: MENU/MENU8.PRG
  target_path: data/MENU/MENU8.PRG
  elf_path: build/data/MENU/MENU8.PRG.elf
  asm_path: build/src/MENU/MENU8.PRG
  src_path: src/MENU/MENU8.PRG
  asset_path: build/assets/MENU/MENU8.PRG
  ld_script_path: build/config/MENU/MENU8.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENU8.PRG/symbol_addrs.txt
    - config/MENU/MENU8.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
    - config/MENU/MAINMENU.PRG/exports.txt
    - config/BATTLE/BATTLE.PRG/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENU8.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENU8.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 88]
      - [0x6C, .rodata, 21A0]
      - [0x88, c]
      - [0x21A0, c]
      - { start: 0x2D58, type: vsStringTable, name: menu, linker_entry: false }
      - { start: 0x35B4, type: vsStringTable, name: rename, linker_entry: false }
      - [0x3704, bss, 88]
  - [0x3754]
