build/data/TITLE/TITLE.PRG.elf: LDSCRIPT += \
	config/SLUS_010.40/exports.txt

build/src/TITLE/TITLE.PRG/22C.o: ASFLAGS += -no-pad-sections
build/src/TITLE/TITLE.PRG/22C.o: CC1VER := 2.8.0
build/src/TITLE/TITLE.PRG/22C.o: build/src/include/lbas.h
