sha1: f74a76e6215edebf607d0c2af56481050edb139a
options:
  basename: TITLE/TITLE.PRG
  target_path: data/TITLE/TITLE.PRG
  elf_path: build/data/TITLE/TITLE.PRG.elf
  asm_path: build/src/TITLE/TITLE.PRG
  src_path: src/TITLE/TITLE.PRG
  asset_path: build/assets/TITLE/TITLE.PRG
  ld_script_path: build/config/TITLE/TITLE.PRG/link.ld
  symbol_addrs_path: 
    - config/TITLE/TITLE.PRG/symbol_addrs.txt
    - config/TITLE/TITLE.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/TITLE/TITLE.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/TITLE/TITLE.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80068800
    align: 4
    subsegments:
      - [0x00, .rodata, 22C]
      - [0x1DC, .rodata, libpress/LIBPRESS]
      - [0x22C, c]
      - [0x959C, c, libpress/LIBPRESS]
      - [0x9C1C, c, libpress/VLC_C]
      - [0x9F9C, c, libpress/BUILD]
      - [0xA08C, .data, 22C]
      - [0xA110, data, 22C]
      - [0xA70C, rgba16, publisherClut, 16, 1]
      - [0xA72C, rgb4, publisher, 256, 48]
      - [0xBF2C, rgb4, developer, 128, 13]
      - [0xC26C, rgba16, developerClut, 16, 2]
      - [0xC2AC, data]
      - [0xC2B4, rgba16, menuItemClut, 16, 2]
      - [0xC2F4, rgba16, _menuItemOutlineClut, 16, 2]
      - [0xC334, data]
      - [0xD344, data, libpress/LIBPRESS]
      - [0xD494, data, libpress/VLC_C]
      - [0xD4C4, .data, libpress/BUILD]
      - [0xE2D4, rgba16Compressed, menuBg, 544, 576]
      - [0x449A8, rgba16, menuCopyright, 180, 24]
      - [0x46B68, rgb4, fontTable0, 256, 220]
      - [0x4D968, rgba16, fontTable0Clut, 16, 16]
      - [0x4DB68, rgb4, fontTable1, 256, 220]
      - [0x54968, rgba16, fontTable1Clut, 16, 16]
      - [0x54B68, rgb4, debugFont, 256, 154]
      - [0x59868, rgba16, debugFontClut, 16, 16]
      - [0x59A68, rgb4, uiTex0, 256, 224]
      - [0x60A68, rgb4, uiTex1, 256, 256]
      - [0x68A68, rgba16, saveMenuBgClut, 256, 1]
      - [0x68C68, rgb8, saveMenuBg, 192, 240]
      - [0x74068, bss]
  - [0x87648]
