sha1: f74a76e6215edebf607d0c2af56481050edb139a
options:
  basename: TITLE/TITLE.PRG
  target_path: data/TITLE/TITLE.PRG
  elf_path: build/data/TITLE/TITLE.PRG.elf
  asm_path: build/src/TITLE/TITLE.PRG
  src_path: src/TITLE/TITLE.PRG
  asset_path: build/assets/TITLE/TITLE.PRG
  ld_script_path: build/config/TITLE/TITLE.PRG/link.ld
  symbol_addrs_path: 
    - config/TITLE/TITLE.PRG/symbol_addrs.txt
    - config/TITLE/TITLE.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/TITLE/TITLE.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/TITLE/TITLE.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80068800
    align: 4
    subsegments:
      - [0x00, .rodata, 22C]
      - [0x1DC, .rodata, libpress/LIBPRESS]
      - [0x22C, c]
      - [0x959C, c, libpress/LIBPRESS]
      - [0x9C1C, c, libpress/VLC_C]
      - [0x9F9C, c, libpress/BUILD]
      - [0xA08C, .data, 22C]
      - [0xA09C, data, 22C]
      - [0x74068, bss]
  - [0x87648]
