sha1: f74a76e6215edebf607d0c2af56481050edb139a
options:
  basename: TITLE/TITLE.PRG
  target_path: data/TITLE/TITLE.PRG
  elf_path: build/data/TITLE/TITLE.PRG.elf
  asm_path: build/src/TITLE/TITLE.PRG
  src_path: src/TITLE/TITLE.PRG
  asset_path: build/assets/TITLE/TITLE.PRG
  ld_script_path: build/config/TITLE/TITLE.PRG/link.ld
  symbol_addrs_path: 
    - config/TITLE/TITLE.PRG/symbol_addrs.txt
    - config/TITLE/TITLE.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/TITLE/TITLE.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/TITLE/TITLE.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80068800
    align: 4
    subsegments:
      - [0x00, .rodata, 22C]
      - [0x1DC, .rodata, libpress/LIBPRESS]
      - [0x22C, c]
      - [0x959C, c, libpress/LIBPRESS]
      - [0x9C1C, c, libpress/VLC_C]
      - [0x9F9C, c, libpress/BUILD]
      - [0xA08C, .data, 22C]
      - {start: 0xA72C, type: rgb4, name: publisher, width: 256, height: 48, linker_entry: false}
      - {start: 0xBF2C, type: rgb4, name: developer, width: 128, height: 13, linker_entry: false}
      - [0xC3D4, data]
      - [0xD344, data, libpress/LIBPRESS]
      - [0xD494, data, libpress/VLC_C]
      - [0xD4C4, .data, libpress/BUILD]
      - [0xE2D4, rgba16Compressed, _titleScreenBg, 544, 576]
      - [0x449A8, rgba16, _menuCopyright, 180, 24]
      - [0x46B68, rgb4, _fontTable, 256, 220]
      - [0x4D968, rgba16, _fontTable0Clut, 16, 16]
      - [0x4DB68, rgb4, _fontTable1, 256, 220]
      - [0x54968, rgba16, _fontTable1Clut, 16, 16]
      - [0x54B68, rgb4, _debugFont, 256, 154]
      - [0x59868, rgba16, _debugFontClut, 16, 16]
      - [0x59A68, rgb4, _uiTable, 256, 480]
      - [0x68A68, rgba16, _saveMenuBg, 256, 1]
      - [0x68C68, rgb8, _saveMenuBgData, 192, 240]
      - [0x74068, .bss, 22C]
  - [0x87648]
