#include "common.h"

INCLUDE_ASM("build/src/EFFECT/PLG065.BIN/nonmatchings/F8", func_800F98F8);

INCLUDE_ASM("build/src/EFFECT/PLG065.BIN/nonmatchings/F8", func_800FA7B0);

INCLUDE_ASM("build/src/EFFECT/PLG065.BIN/nonmatchings/F8", func_800FB71C);

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FC340
#define VS_PARTICLE_TARGET_FUNCTION func_800FCAC8
#define VS_PARTICLE_CONTROL_FUNCTION func_800FCCE0
#define VS_PARTICLE_RENDER_FUNCTION func_800FD190
#define VS_PARTICLE_CORNER_STATE D_800FD974
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

INCLUDE_ASM("build/src/EFFECT/PLG065.BIN/nonmatchings/F8", func_800FD190);

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FC340
#define VS_PARTICLE_TARGET_FUNCTION func_800FCAC8
#define VS_PARTICLE_CONTROL_FUNCTION func_800FCCE0
#define VS_PARTICLE_RENDER_FUNCTION func_800FD190
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FD6C0
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"
