sha1: 0a4be907048de046bd2e5c7f633e3bf4fedbb379
options:
  basename: EFFECT/PLG170.BIN
  target_path: data/EFFECT/PLG170.BIN
  elf_path: build/data/EFFECT/PLG170.BIN.elf
  asm_path: build/src/EFFECT/PLG170.BIN
  src_path: src/EFFECT/PLG170.BIN
  asset_path: build/assets/EFFECT/PLG170.BIN
  ld_script_path: build/config/EFFECT/PLG170.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG170.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG170.BIN/undefined_syms_auto.txt


segments:
  - name: PLG170.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 18]
    - [0x18, c]
    - [0x4DC4, data, 18]
  - [0x5304]
