sha1: 97af1e332c3d9b7b314be03d3aa90ac7fea92ece
options:
  basename: EFFECT/PLG045.BIN
  target_path: data/EFFECT/PLG045.BIN
  elf_path: build/data/EFFECT/PLG045.BIN.elf
  asm_path: build/src/EFFECT/PLG045.BIN
  src_path: src/EFFECT/PLG045.BIN
  asset_path: build/assets/EFFECT/PLG045.BIN
  ld_script_path: build/config/EFFECT/PLG045.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG045.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG045.BIN/undefined_syms_auto.txt


segments:
  - name: PLG045.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0x0, .rodata, 110]
    - [0x110, c]
    - [0x1DB4, data, 110]
  - [0x1DB8]
