sha1: 6a19aebfe2624796ad540e4544d8772e9a77958f
options:
  basename: EFFECT/PLG087.BIN
  target_path: data/EFFECT/PLG087.BIN
  elf_path: build/data/EFFECT/PLG087.BIN.elf
  asm_path: build/src/EFFECT/PLG087.BIN
  src_path: src/EFFECT/PLG087.BIN
  asset_path: build/assets/EFFECT/PLG087.BIN
  ld_script_path: build/config/EFFECT/PLG087.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG087.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG087.BIN/undefined_syms_auto.txt


segments:
  - name: PLG087.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 1F0]
    - [0x1F0, c]
    - [0x5F5C, data, 1F0]
  - [0x6204]
