sha1: ea8e6794ecc55d25650855cf774e501f1b6ff5bd
options:
  basename: EFFECT/PLG224.BIN
  target_path: data/EFFECT/PLG224.BIN
  elf_path: build/data/EFFECT/PLG224.BIN.elf
  asm_path: build/src/EFFECT/PLG224.BIN
  src_path: src/EFFECT/PLG224.BIN
  asset_path: build/assets/EFFECT/PLG224.BIN
  ld_script_path: build/config/EFFECT/PLG224.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG224.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG224.BIN/undefined_syms_auto.txt


segments:
  - name: PLG224.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, F8]
    - [0xF8, c]
    - [0x16EC, data, F8]
  - [0x16F0]
