#include "common.h"

INCLUDE_ASM("build/src/EFFECT/PLG073.BIN/nonmatchings/F8", func_800F98F8);

INCLUDE_ASM("build/src/EFFECT/PLG073.BIN/nonmatchings/F8", func_800FA7F0);

#define VS_TRAIL_ORIGIN_FUNCTION func_800FB414
#define VS_TRAIL_TARGET_FUNCTION func_800FBBB0
#define VS_TRAIL_CONTROL_FUNCTION func_800FBDC8
#define VS_TRAIL_INIT_FUNCTION func_800FC28C
#define VS_TRAIL_UPDATE_FUNCTION func_800FC404
#define VS_TRAIL_RENDER_FUNCTION func_800FC590
#define VS_TRAIL_DISPATCH_FUNCTION func_800FCFEC
#define VS_TRAIL_CORNER_STATE D_800FEF7C
#include "src/EFFECT/trails5.h"

INCLUDE_ASM("build/src/EFFECT/PLG073.BIN/nonmatchings/F8", func_800FD534);

#define VS_GRID_FUNCTION func_800FE3EC
#include "src/EFFECT/grids.h"
