sha1: 3feb447ee4758840a6ee626595d64e2398986f3e
options:
  basename: EFFECT/PLG085.BIN
  target_path: data/EFFECT/PLG085.BIN
  elf_path: build/data/EFFECT/PLG085.BIN.elf
  asm_path: build/src/EFFECT/PLG085.BIN
  src_path: src/EFFECT/PLG085.BIN
  asset_path: build/assets/EFFECT/PLG085.BIN
  ld_script_path: build/config/EFFECT/PLG085.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG085.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG085.BIN/undefined_syms_auto.txt


segments:
  - name: PLG085.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 18]
    - [0x18, c]
    - [0x1A60, data, 18]
  - [0x1A80]
