sha1: 364de35cb5d94da6f3545951277acd89e8796e69
options:
  basename: MENU/MAINMENU.PRG
  target_path: data/MENU/MAINMENU.PRG
  elf_path: build/data/MENU/MAINMENU.PRG.elf
  asm_path: build/src/MENU/MAINMENU.PRG
  src_path: src/MENU/MAINMENU.PRG
  asset_path: build/assets/MENU/MAINMENU.PRG
  ld_script_path: build/config/MENU/MAINMENU.PRG/link.ld
  create_undefined_funcs_auto: false
  create_undefined_syms_auto: false
  undefined_funcs_auto_path: build/config/MENU/MAINMENU.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MAINMENU.PRG/undefined_syms_auto.txt
  subalign: 4
  auto_link_sections: [.rodata, .data, .bss]

segments:
  - start: 0x0
    type: code
    vram: 0x800F9800
    align: 1
    subsegments:
      - [0x224, c]
      - [0xC48, c]
      - [0x2D10, c]
      - [0x58EC, c]
  - [0x8D79]
