build/data/BATTLE/INITBTL.PRG.elf: LDSCRIPT += \
	config/SLUS_010.40/exports.txt
build/src/BATTLE/INITBTL.PRG/%.o: ASFLAGS += -no-pad-sections
build/src/BATTLE/INITBTL.PRG/%.o: CC1VER := 2.8.0
build/src/BATTLE/INITBTL.PRG/18.o: build/src/include/lbas.h