$(BUILD)/data/BATTLE/INITBTL.PRG.elf: LDSCRIPT += \
	config/SLUS_010.40/exports.txt
$(BUILD)/src/BATTLE/INITBTL.PRG/%.o: ASFLAGS += -no-pad-sections
$(BUILD)/src/BATTLE/INITBTL.PRG/%.o: CC1VER := 2.8.0
$(BUILD)/src/BATTLE/INITBTL.PRG/18.o: $(BUILD)/src/include/lbas.h