name: &n BATTLE/INITBTL.PRG
sha1: d7ea16ef957179cad6e3b02727bb714713cfcc32
options:
  basename: *n
  base_path: ../../..
  target_path: data/BATTLE/INITBTL.PRG
  elf_path: build/data/BATTLE/INITBTL.PRG.elf
  platform: psx
  compiler: PSYQ

  asm_path: build/src/BATTLE/INITBTL.PRG
  data_path: ""
  src_path: src/BATTLE/INITBTL.PRG
  asset_path: build/assets/BATTLE/INITBTL.PRG
  extensions_path: tools/splat_ext

  hasm_in_src_path: true
  o_as_suffix: true

  ld_dependencies: true
  ld_script_path: build/config/BATTLE/INITBTL.PRG/link.ld

  find_file_boundaries: true
  gp_value: 0x80033674
  image_type_in_extension: true

  section_order: [.rodata, .text, .data]
  auto_link_sections: [.data, .rodata]

  symbol_addrs_path: 
    - config/BATTLE/INITBTL.PRG/symbol_addrs.txt
    - config/BATTLE/INITBTL.PRG/exports.txt
    - config/SLUS_010.40/exports.txt

  undefined_funcs_auto_path: build/config/BATTLE/INITBTL.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/BATTLE/INITBTL.PRG/undefined_syms_auto.txt

  subalign: 2

  string_encoding: &enc ASCII
  data_string_encoding: *enc
  rodata_string_guesser_level: &strLvl 2
  data_string_guesser_level: *strLvl

segments:
  - start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
      - [0x00, rodata]
      - [0x18, c]
      - [0x1318, data]
  - [0x1B7C]
