sha1: d7ea16ef957179cad6e3b02727bb714713cfcc32
options:
  basename: BATTLE/INITBTL.PRG
  target_path: data/BATTLE/INITBTL.PRG
  elf_path: build/data/BATTLE/INITBTL.PRG.elf
  asm_path: build/src/BATTLE/INITBTL.PRG
  src_path: src/BATTLE/INITBTL.PRG
  asset_path: build/assets/BATTLE/INITBTL.PRG
  ld_script_path: build/config/BATTLE/INITBTL.PRG/link.ld
  symbol_addrs_path: 
    - config/BATTLE/INITBTL.PRG/symbol_addrs.txt
    - config/BATTLE/INITBTL.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/BATTLE/INITBTL.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/BATTLE/INITBTL.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
      - [0x00, rodata]
      - [0x18, c]
      - [0x1318, data]
  - [0x1B7C]
