#include "common.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800F9A08
#define VS_PARTICLE_TARGET_FUNCTION func_800FA190
#define VS_PARTICLE_CONTROL_FUNCTION func_800FA3A8
#define VS_PARTICLE_RENDER_FUNCTION func_800FA858
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FB418
#define VS_PARTICLE_CORNER_STATE D_800FCCA0
#include "src/EFFECT/particleSetup.h"

#include "src/EFFECT/particleRender.h"

#include "src/EFFECT/particleDispatch.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FB6AC
#define VS_PARTICLE_TARGET_FUNCTION func_800FBE34
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC04C
#define VS_PARTICLE_RENDER_FUNCTION func_800FC4FC
#define VS_PARTICLE_CORNER_STATE D_800FCCA4
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

#define VS_PARTICLE_RENDER_FUNCTION func_800FC4FC
#include "src/EFFECT/particleLineRender.h"
#undef VS_PARTICLE_RENDER_FUNCTION

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FB6AC
#define VS_PARTICLE_TARGET_FUNCTION func_800FBE34
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC04C
#define VS_PARTICLE_RENDER_FUNCTION func_800FC4FC
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FCA2C
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"
