sha1: 46ff0ff5743e9c300ed27c1d4759075fe35e02d5
options:
  basename: MENU/MENUF.PRG
  target_path: data/MENU/MENUF.PRG
  elf_path: build/data/MENU/MENUF.PRG.elf
  asm_path: build/src/MENU/MENUF.PRG
  src_path: src/MENU/MENUF.PRG
  asset_path: build/assets/MENU/MENUF.PRG
  ld_script_path: build/config/MENU/MENUF.PRG/link.ld
  create_undefined_funcs_auto: false
  create_undefined_syms_auto: false
  auto_link_sections: [.rodata, .data, .bss]

segments:
  - name: MENUF.PRG
    start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 3B8]
      - [0x3B8, c]
  - [0x71F8]
