$(BUILD)/src/MENU/MENUC.PRG/%.o: ASFLAGS += -no-pad-sections
$(BUILD)/src/MENU/MENUC.PRG/%.o: CC1VER := 2.8.0-psx

$(BUILD)/config/MENU/MENUC.PRG/link.d: \
	config/SLUS_010.40/symbol_addrs.txt \
	config/BATTLE/BATTLE.PRG/symbol_addrs.txt \
	config/MENU/MAINMENU.PRG/symbol_addrs.txt