sha1: 66eb6bfcdf6c8ec9ee1672da4824f6ebb7e9459a
options:
  basename: MENU/MENUC.PRG
  target_path: data/MENU/MENUC.PRG
  elf_path: build/data/MENU/MENUC.PRG.elf
  asm_path: build/src/MENU/MENUC.PRG
  src_path: src/MENU/MENUC.PRG
  asset_path: build/assets/MENU/MENUC.PRG
  ld_script_path: build/config/MENU/MENUC.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENUC.PRG/symbol_addrs.txt
    - config/MENU/MENUC.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENUC.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENUC.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 168]
      - [0x168, c]
      - [0x9320, data, 168]
      - [0x93F4, bss, 168]
  - [0x9594]
