name: &n MENU/MENUC.PRG
sha1: 66eb6bfcdf6c8ec9ee1672da4824f6ebb7e9459a
options:
  basename: *n
  base_path: ../../..
  target_path: data/MENU/MENUC.PRG
  elf_path: build/data/MENU/MENUC.PRG.elf
  platform: psx
  compiler: PSYQ

  asm_path: build/src/MENU/MENUC.PRG
  data_path: ""
  src_path: src/MENU/MENUC.PRG
  asset_path: build/assets/MENU/MENUC.PRG
  extensions_path: tools/splat_ext

  hasm_in_src_path: true
  o_as_suffix: true

  ld_dependencies: true
  ld_script_path: build/config/MENU/MENUC.PRG/link.ld

  find_file_boundaries: true
  gp_value: 0x80033674
  image_type_in_extension: true

  section_order: [.rodata, .text, .data]
  auto_link_sections: [.data, .rodata]

  symbol_addrs_path: 
    - config/MENU/MENUC.PRG/symbol_addrs.txt
    - config/MENU/MENUC.PRG/exports.txt

  undefined_funcs_auto_path: build/config/MENU/MENUC.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENUC.PRG/undefined_syms_auto.txt

  subalign: 2

  string_encoding: &enc ASCII
  data_string_encoding: *enc
  rodata_string_guesser_level: &strLvl 2
  data_string_guesser_level: *strLvl

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 168]
      - [0x168, c]
      - [0x9320, data, 168]
      - [0x93F4, bss, 168]
  - [0x9594]
