sha1: 80cb78a68cbb5c57f26c14c292fae0979eee8716
options:
  basename: EFFECT/PLG137.BIN
  target_path: data/EFFECT/PLG137.BIN
  elf_path: build/data/EFFECT/PLG137.BIN.elf
  asm_path: build/src/EFFECT/PLG137.BIN
  src_path: src/EFFECT/PLG137.BIN
  asset_path: build/assets/EFFECT/PLG137.BIN
  ld_script_path: build/config/EFFECT/PLG137.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG137.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG137.BIN/undefined_syms_auto.txt


segments:
  - name: PLG137.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, F8]
    - [0xF8, c]
    - [0x476C, data, F8]
  - [0x4860]
