$(BUILD)/data/MENU/MENU3.PRG.elf: LDSCRIPT += \
	config/SLUS_010.40/exports.txt \
	config/BATTLE/BATTLE.PRG/exports.txt \
	config/MENU/MAINMENU.PRG/exports.txt
$(BUILD)/src/MENU/MENU3.PRG/%.o: ASFLAGS += -no-pad-sections
$(BUILD)/src/MENU/MENU3.PRG/%.o: CC1VER := 2.8.0-psx
