sha1: df342d3ceecd73a259f3c346e5f0668ed330719d
options:
  basename: EFFECT/PLG086.BIN
  target_path: data/EFFECT/PLG086.BIN
  elf_path: build/data/EFFECT/PLG086.BIN.elf
  asm_path: build/src/EFFECT/PLG086.BIN
  src_path: src/EFFECT/PLG086.BIN
  asset_path: build/assets/EFFECT/PLG086.BIN
  ld_script_path: build/config/EFFECT/PLG086.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG086.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG086.BIN/undefined_syms_auto.txt


segments:
  - name: PLG086.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, F8]
    - [0xF8, c]
    - [0x4B90, data, F8]
  - [0x4BB4]
