name: &n BATTLE/BATTLE.PRG
sha1: d53aaccc3b3a2fc057d05e0dcea92f7182bc72a9
options:
  basename: *n
  base_path: ../../..
  target_path: data/BATTLE/BATTLE.PRG
  elf_path: build/data/BATTLE/BATTLE.PRG.elf
  platform: psx
  compiler: GCC

  asm_path: build/src/BATTLE/BATTLE.PRG
  data_path: ""
  src_path: src/BATTLE/BATTLE.PRG
  asset_path: build/assets/BATTLE/BATTLE.PRG
  extensions_path: tools/splat_ext

  ld_dependencies: true
  o_as_suffix: true

  ld_script_path: build/config/BATTLE/BATTLE.PRG/link.ld

  find_file_boundaries: true
  gp_value: 0x80033674
  image_type_in_extension: true

  section_order: [.rodata, .text, .data]
  auto_link_sections: [.data, .rodata]

  symbol_addrs_path: 
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/exports.txt
    - config/SLUS_010.40/exports.txt

  undefined_funcs_auto_path: build/config/BATTLE/BATTLE.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/BATTLE/BATTLE.PRG/undefined_syms_auto.txt

  subalign: 2

  string_encoding: &enc ASCII
  data_string_encoding: *enc
  rodata_string_guesser_level: &strLvl 2
  data_string_guesser_level: *strLvl

segments:
  - start: 0x0
    type: code
    vram: 0x80068800
    align: 4
    subsegments:
      - [0x00, rodata]
      - [0x6C4, rodata]
      - [0xC30, rodata]
      - [0xC7C, rodata]
      - [0xCF0, rodata]
      - [0xDF4, rodata]
      - [0x1010, rodata]
      - [0x1024, rodata]
      - [0x10F8, rodata]
      - [0x1354, rodata]
      - [0x146C, asm]
      - [0x7F984, data]
  - [0x8D124]
