#include "common.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800F9AE8
#define VS_PARTICLE_TARGET_FUNCTION func_800FA270
#define VS_PARTICLE_CONTROL_FUNCTION func_800FA488
#define VS_PARTICLE_RENDER_FUNCTION func_800FA938
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FB4F8
#define VS_PARTICLE_CORNER_STATE D_800FEEA0
#include "src/EFFECT/particleSetup.h"

#include "src/EFFECT/particleRender.h"

#include "src/EFFECT/particleDispatch.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FB78C
#define VS_PARTICLE_TARGET_FUNCTION func_800FBF14
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC12C
#define VS_PARTICLE_RENDER_FUNCTION func_800FC5DC
#define VS_PARTICLE_CORNER_STATE D_800FEEA4
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

#define VS_PARTICLE_RENDER_FUNCTION func_800FC5DC
#include "src/EFFECT/particleLineRender.h"
#undef VS_PARTICLE_RENDER_FUNCTION

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FB78C
#define VS_PARTICLE_TARGET_FUNCTION func_800FBF14
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC12C
#define VS_PARTICLE_RENDER_FUNCTION func_800FC5DC
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FCB0C
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"

#define VS_TRAIL_ORIGIN_FUNCTION func_800FCD80
#define VS_TRAIL_TARGET_FUNCTION func_800FD51C
#define VS_TRAIL_CONTROL_FUNCTION func_800FD734
#define VS_TRAIL_INIT_FUNCTION func_800FDBF8
#define VS_TRAIL_UPDATE_FUNCTION func_800FDD70
#define VS_TRAIL_RENDER_FUNCTION func_800FDEFC
#define VS_TRAIL_DISPATCH_FUNCTION func_800FE958
#define VS_TRAIL_CORNER_STATE D_800FEEA8
#include "src/EFFECT/trails5.h"
