#include "common.h"

#define VS_SURFACE_FUNCTION func_800F99F0
#define VS_SURFACE_VERTICES D_800FF75C
#define VS_SURFACE_REPEAT
#include "src/EFFECT/surfaces.h"

INCLUDE_ASM("build/src/EFFECT/PLG087.BIN/nonmatchings/1F0", func_800FA588);

#define VS_GRID_FUNCTION func_800FB4F8
#include "src/EFFECT/grids.h"

#define VS_TRAIL_ORIGIN_FUNCTION func_800FC048
#define VS_TRAIL_TARGET_FUNCTION func_800FC7E4
#define VS_TRAIL_CONTROL_FUNCTION func_800FC9FC
#define VS_TRAIL_INIT_FUNCTION func_800FCEC0
#define VS_TRAIL_UPDATE_FUNCTION func_800FD038
#define VS_TRAIL_RENDER_FUNCTION func_800FD1C4
#define VS_TRAIL_DISPATCH_FUNCTION func_800FDC20
#define VS_TRAIL_CORNER_STATE D_800FF9FC
#include "src/EFFECT/trails5.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FE168
#define VS_PARTICLE_TARGET_FUNCTION func_800FE8F0
#define VS_PARTICLE_CONTROL_FUNCTION func_800FEB08
#define VS_PARTICLE_RENDER_FUNCTION func_800FEFB8
#define VS_PARTICLE_CORNER_STATE D_800FFA00
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

#define VS_PARTICLE_RENDER_FUNCTION func_800FEFB8
#include "src/EFFECT/particleLineRender.h"
#undef VS_PARTICLE_RENDER_FUNCTION

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FE168
#define VS_PARTICLE_TARGET_FUNCTION func_800FE8F0
#define VS_PARTICLE_CONTROL_FUNCTION func_800FEB08
#define VS_PARTICLE_RENDER_FUNCTION func_800FEFB8
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FF4E8
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"
