#include "common.h"

INCLUDE_ASM("build/src/EFFECT/PLG069.BIN/nonmatchings/E0", func_800F98E0);

#define VS_TRAIL_ORIGIN_FUNCTION func_800FA3EC
#define VS_TRAIL_TARGET_FUNCTION func_800FAB88
#define VS_TRAIL_CONTROL_FUNCTION func_800FADA0
#define VS_TRAIL_INIT_FUNCTION func_800FB278
#define VS_TRAIL_UPDATE_FUNCTION func_800FB3F0
#define VS_TRAIL_RENDER_FUNCTION func_800FB57C
#define VS_TRAIL_DISPATCH_FUNCTION func_800FBFCC
#define VS_TRAIL_CORNER_STATE D_800FD4D4
#include "src/EFFECT/trails9.h"

INCLUDE_ASM("build/src/EFFECT/PLG069.BIN/nonmatchings/E0", func_800FC50C);
