options:
  platform: psx
  compiler: PSYQ
  base_path: ../
  data_path: ""
  extensions_path: tools/splat_ext
  hasm_in_src_path: true
  o_as_suffix: true
  ld_dependencies: true
  find_file_boundaries: true
  image_type_in_extension: true
  gp_value: 0x80033674
  section_order: [.rodata, .text, .data, .bss]
  auto_link_sections: [.data, .rodata]
  subalign: 2
  string_encoding: &enc ASCII
  data_string_encoding: *enc
  rodata_string_guesser_level: &strLvl 2
  data_string_guesser_level: *strLvl
