sha1: 9f729cc23c2c23f2847276703891d0e46cc9ade2
options:
  basename: MENU/MENUE.PRG
  target_path: data/MENU/MENUE.PRG
  elf_path: build/data/MENU/MENUE.PRG.elf
  asm_path: build/src/MENU/MENUE.PRG
  src_path: src/MENU/MENUE.PRG
  asset_path: build/assets/MENU/MENUE.PRG
  ld_script_path: build/config/MENU/MENUE.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENUE.PRG/symbol_addrs.txt
    - config/MENU/MENUE.PRG/exports.txt
    - config/MENU/MAINMENU.PRG/exports.txt
    - config/BATTLE/BATTLE.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENUE.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENUE.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 494]
      - [0x494, c, 494]
      - [0x2654, data, 494]
      - [0x2A30, bss, 494]
  - [0x2A5C]
