name: &n MENU/MENUE.PRG
sha1: 9f729cc23c2c23f2847276703891d0e46cc9ade2
options:
  basename: *n
  base_path: ../../..
  target_path: data/MENU/MENUE.PRG
  elf_path: build/data/MENU/MENUE.PRG.elf
  platform: psx
  compiler: PSYQ

  asm_path: build/src/MENU/MENUE.PRG
  data_path: ""
  src_path: src/MENU/MENUE.PRG
  asset_path: build/assets/MENU/MENUE.PRG
  extensions_path: tools/splat_ext

  hasm_in_src_path: true
  o_as_suffix: true

  ld_dependencies: true
  ld_script_path: build/config/MENU/MENUE.PRG/link.ld

  find_file_boundaries: true
  gp_value: 0x80033674
  image_type_in_extension: true

  section_order: [.rodata, .text, .data]
  auto_link_sections: [.data, .rodata]

  symbol_addrs_path: 
    - config/MENU/MENUE.PRG/symbol_addrs.txt
    - config/MENU/MENUE.PRG/exports.txt
    - config/SLUS_010.40/exports.txt

  undefined_funcs_auto_path: build/config/MENU/MENUE.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENUE.PRG/undefined_syms_auto.txt

  subalign: 2

  string_encoding: &enc ASCII
  data_string_encoding: *enc
  rodata_string_guesser_level: &strLvl 2
  data_string_guesser_level: *strLvl

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 494]
      - [0x494, c, 494]
      - [0x2654, data, 494]
      - [0x2A30, bss, 494]
  - [0x2A5C]
