sha1: c0dbe52e9e6d268f2b4e4e42bf717347cbe7272c
options:
  basename: EFFECT/PLG047.BIN
  target_path: data/EFFECT/PLG047.BIN
  elf_path: build/data/EFFECT/PLG047.BIN.elf
  asm_path: build/src/EFFECT/PLG047.BIN
  src_path: src/EFFECT/PLG047.BIN
  asset_path: build/assets/EFFECT/PLG047.BIN
  ld_script_path: build/config/EFFECT/PLG047.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG047.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG047.BIN/undefined_syms_auto.txt


segments:
  - name: PLG047.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0xF6C, data, 0]
  - [0xF8C]
