sha1: 98c377c70bdb95d2a42d033e26c83aef77dd0a39
options:
  basename: EFFECT/PLG158.BIN
  target_path: data/EFFECT/PLG158.BIN
  elf_path: build/data/EFFECT/PLG158.BIN.elf
  asm_path: build/src/EFFECT/PLG158.BIN
  src_path: src/EFFECT/PLG158.BIN
  asset_path: build/assets/EFFECT/PLG158.BIN
  ld_script_path: build/config/EFFECT/PLG158.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG158.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG158.BIN/undefined_syms_auto.txt


segments:
  - name: PLG158.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0x3638, data, 0]
  - [0x3B58]
