sha1: 5054ad93a197a160f053546834cac394a0ddaf7b
options:
  basename: EFFECT/PLG263.BIN
  target_path: data/EFFECT/PLG263.BIN
  elf_path: build/data/EFFECT/PLG263.BIN.elf
  asm_path: build/src/EFFECT/PLG263.BIN
  src_path: src/EFFECT/PLG263.BIN
  asset_path: build/assets/EFFECT/PLG263.BIN
  ld_script_path: build/config/EFFECT/PLG263.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG263.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG263.BIN/undefined_syms_auto.txt


segments:
  - name: PLG263.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 110]
    - [0x110, c]
    - [0x44B0, data, 110]
  - [0x4774]
