sha1: cf16e6330ec461b23cd0f9ff64dd833f46bef13b
options:
  basename: EFFECT/PLG148.BIN
  target_path: data/EFFECT/PLG148.BIN
  elf_path: build/data/EFFECT/PLG148.BIN.elf
  asm_path: build/src/EFFECT/PLG148.BIN
  src_path: src/EFFECT/PLG148.BIN
  asset_path: build/assets/EFFECT/PLG148.BIN
  ld_script_path: build/config/EFFECT/PLG148.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG148.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG148.BIN/undefined_syms_auto.txt


segments:
  - name: PLG148.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, E0]
    - [0xE0, c]
    - [0x30F8, data, E0]
  - [0x311C]
