sha1: 9d8df778383edcd919e0338d78ce4de8d0792b40
options:
  basename: EFFECT/PLG134.BIN
  target_path: data/EFFECT/PLG134.BIN
  elf_path: build/data/EFFECT/PLG134.BIN.elf
  asm_path: build/src/EFFECT/PLG134.BIN
  src_path: src/EFFECT/PLG134.BIN
  asset_path: build/assets/EFFECT/PLG134.BIN
  ld_script_path: build/config/EFFECT/PLG134.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG134.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG134.BIN/undefined_syms_auto.txt


segments:
  - name: PLG134.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, E0]
    - [0xE0, c]
    - [0x3170, data, E0]
  - [0x3190]
