build/data/ENDING/ENDING.PRG.elf: LDSCRIPT += \
	config/SLUS_010.40/exports.txt
build/src/ENDING/ENDING.PRG/D4.o: build/src/include/lbas.h
build/src/ENDING/ENDING.PRG/D4.o: ASFLAGS += -no-pad-sections
build/src/ENDING/ENDING.PRG/D4.o: CC1VER := 2.8.0

build/src/ENDING/ENDING.PRG/illustLbas.o: build/src/include/lbas.h
