$(BUILD)/data/ENDING/ENDING.PRG.elf: LDSCRIPT += \
	config/SLUS_010.40/exports.txt
$(BUILD)/src/ENDING/ENDING.PRG/D4.o: $(BUILD)/src/include/lbas.h
$(BUILD)/src/ENDING/ENDING.PRG/D4.o: ASFLAGS += -no-pad-sections
$(BUILD)/src/ENDING/ENDING.PRG/D4.o: CC1VER := 2.8.0-psx

$(BUILD)/src/ENDING/ENDING.PRG/illustLbas.o: $(BUILD)/src/include/lbas.h
