#define VS_PARTICLE_ORIGIN_FUNCTION func_800F9910
#define VS_PARTICLE_TARGET_FUNCTION func_800FA098
#define VS_PARTICLE_CONTROL_FUNCTION func_800FA2B0
#define VS_PARTICLE_RENDER_FUNCTION func_800FA760
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FB320
#define VS_PARTICLE_CORNER_STATE D_800FB5B4
#include "src/EFFECT/particleSetup.h"

#include "src/EFFECT/particleRender.h"

#include "src/EFFECT/particleDispatch.h"
