sha1: 0d7d80922cee0f20d0c514449b99e7f708aa8708
options:
  basename: EFFECT/PLG077.BIN
  target_path: data/EFFECT/PLG077.BIN
  elf_path: build/data/EFFECT/PLG077.BIN.elf
  asm_path: build/src/EFFECT/PLG077.BIN
  src_path: src/EFFECT/PLG077.BIN
  asset_path: build/assets/EFFECT/PLG077.BIN
  ld_script_path: build/config/EFFECT/PLG077.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG077.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG077.BIN/undefined_syms_auto.txt


segments:
  - name: PLG077.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 18]
    - [0x18, c]
    - [0x40E8, data, 18]
  - [0x4478]
