#include "common.h"

#define VS_TRAIL_ORIGIN_FUNCTION func_800F99D8
#define VS_TRAIL_TARGET_FUNCTION func_800FA174
#define VS_TRAIL_CONTROL_FUNCTION func_800FA38C
#define VS_TRAIL_INIT_FUNCTION func_800FA850
#define VS_TRAIL_UPDATE_FUNCTION func_800FA9C8
#define VS_TRAIL_RENDER_FUNCTION func_800FAB54
#define VS_TRAIL_DISPATCH_FUNCTION func_800FB5B0
#define VS_TRAIL_CORNER_STATE D_800FD0EC
#include "src/EFFECT/trails5.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FBAF8
#define VS_PARTICLE_TARGET_FUNCTION func_800FC280
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC498
#define VS_PARTICLE_RENDER_FUNCTION func_800FC948
#define VS_PARTICLE_CORNER_STATE D_800FD0F0
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

#define VS_PARTICLE_RENDER_FUNCTION func_800FC948
#include "src/EFFECT/particleLineRender.h"
#undef VS_PARTICLE_RENDER_FUNCTION

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FBAF8
#define VS_PARTICLE_TARGET_FUNCTION func_800FC280
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC498
#define VS_PARTICLE_RENDER_FUNCTION func_800FC948
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FCE78
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"
