#include "common.h"

INCLUDE_ASM("build/src/EFFECT/PLG265.BIN/nonmatchings/2E8", func_800F9AE8);

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FA9E0
#define VS_PARTICLE_TARGET_FUNCTION func_800FB168
#define VS_PARTICLE_CONTROL_FUNCTION func_800FB380
#define VS_PARTICLE_RENDER_FUNCTION func_800FB830
#define VS_PARTICLE_CORNER_STATE D_800FFDB8
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

#define VS_PARTICLE_RENDER_FUNCTION func_800FB830
#include "src/EFFECT/particleLineRender.h"
#undef VS_PARTICLE_RENDER_FUNCTION

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FA9E0
#define VS_PARTICLE_TARGET_FUNCTION func_800FB168
#define VS_PARTICLE_CONTROL_FUNCTION func_800FB380
#define VS_PARTICLE_RENDER_FUNCTION func_800FB830
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FBD60
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"

#define VS_TRAIL_ORIGIN_FUNCTION func_800FBFD4
#define VS_TRAIL_TARGET_FUNCTION func_800FC770
#define VS_TRAIL_CONTROL_FUNCTION func_800FC988
#define VS_TRAIL_INIT_FUNCTION func_800FCE4C
#define VS_TRAIL_UPDATE_FUNCTION func_800FCFC4
#define VS_TRAIL_RENDER_FUNCTION func_800FD150
#define VS_TRAIL_DISPATCH_FUNCTION func_800FDBAC
#define VS_TRAIL_CORNER_STATE D_800FFDBC
#include "src/EFFECT/trails5.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FE0F4
#define VS_PARTICLE_TARGET_FUNCTION func_800FE87C
#define VS_PARTICLE_CONTROL_FUNCTION func_800FEA94
#define VS_PARTICLE_RENDER_FUNCTION func_800FEF44
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FFB04
#define VS_PARTICLE_CORNER_STATE D_800FFDC0
#include "src/EFFECT/particleSetup.h"

#include "src/EFFECT/particleRender.h"

#include "src/EFFECT/particleDispatch.h"
