sha1: 7366338469c95f840424e653585c886f7ba772ff
options:
  basename: EFFECT/PLG236.BIN
  target_path: data/EFFECT/PLG236.BIN
  elf_path: build/data/EFFECT/PLG236.BIN.elf
  asm_path: build/src/EFFECT/PLG236.BIN
  src_path: src/EFFECT/PLG236.BIN
  asset_path: build/assets/EFFECT/PLG236.BIN
  ld_script_path: build/config/EFFECT/PLG236.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG236.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG236.BIN/undefined_syms_auto.txt


segments:
  - name: PLG236.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0x3990, data, 0]
  - [0x39F0]
