sha1: 882aacf8dc4b2a6ac02907cdd9996b682e0b5460
options:
  basename: EFFECT/PLG052.BIN
  target_path: data/EFFECT/PLG052.BIN
  elf_path: build/data/EFFECT/PLG052.BIN.elf
  asm_path: build/src/EFFECT/PLG052.BIN
  src_path: src/EFFECT/PLG052.BIN
  asset_path: build/assets/EFFECT/PLG052.BIN
  ld_script_path: build/config/EFFECT/PLG052.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG052.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG052.BIN/undefined_syms_auto.txt


segments:
  - name: PLG052.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0xF70, data, 0]
  - [0xF90]
