$(BUILD)/src/MENU/MENUD.PRG/234.o: ASFLAGS += -no-pad-sections
$(BUILD)/src/MENU/MENUD.PRG/234.o: CC1VER := 2.8.0-psx
$(BUILD)/src/MENU/MENUD.PRG/234.o: $(BUILD)/assets/MENU/ITEMHELP.BIN.h

$(BUILD)/config/MENU/MENUD.PRG/link.d: \
	config/SLUS_010.40/symbol_addrs.txt \
	config/BATTLE/BATTLE.PRG/symbol_addrs.txt \
	config/MENU/MAINMENU.PRG/symbol_addrs.txt