sha1: 0ffc480d1645a4376ddcbe6a1e8a8f1a31973ff4
options:
  basename: MENU/MENUD.PRG
  target_path: data/MENU/MENUD.PRG
  elf_path: build/data/MENU/MENUD.PRG.elf
  asm_path: build/src/MENU/MENUD.PRG
  src_path: src/MENU/MENUD.PRG
  asset_path: build/assets/MENU/MENUD.PRG
  ld_script_path: build/config/MENU/MENUD.PRG/link.ld
  symbol_addrs_path: 
    - config/MENU/MENUD.PRG/symbol_addrs.txt
    - config/MENU/MENUD.PRG/exports.txt
    - config/SLUS_010.40/exports.txt
  undefined_funcs_auto_path: build/config/MENU/MENUD.PRG/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/MENU/MENUD.PRG/undefined_syms_auto.txt

segments:
  - start: 0x0
    type: code
    vram: 0x80102800
    align: 4
    subsegments:
      - [0x0, .rodata, 234]
      - [0x234, c]
      - [0x6D2C, data, 234]
      - [0x7230, bss, 234]
  - [0x7290]
