sha1: 6653fc935dad25a1580c2144a1f3fed49e2d70e8
options:
  basename: EFFECT/PLG169.BIN
  target_path: data/EFFECT/PLG169.BIN
  elf_path: build/data/EFFECT/PLG169.BIN.elf
  asm_path: build/src/EFFECT/PLG169.BIN
  src_path: src/EFFECT/PLG169.BIN
  asset_path: build/assets/EFFECT/PLG169.BIN
  ld_script_path: build/config/EFFECT/PLG169.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG169.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG169.BIN/undefined_syms_auto.txt


segments:
  - name: PLG169.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, E0]
    - [0xE0, c]
    - [0x3D90, data, E0]
  - [0x3DD4]
