#include "common.h"

#define VS_TRAIL_ORIGIN_FUNCTION func_800F99F0
#define VS_TRAIL_TARGET_FUNCTION func_800FA18C
#define VS_TRAIL_CONTROL_FUNCTION func_800FA3A4
#define VS_TRAIL_INIT_FUNCTION func_800FA87C
#define VS_TRAIL_UPDATE_FUNCTION func_800FA9F4
#define VS_TRAIL_RENDER_FUNCTION func_800FAB80
#define VS_TRAIL_DISPATCH_FUNCTION func_800FB5D0
#define VS_TRAIL_CORNER_STATE D_800FDC54
#include "src/EFFECT/trails9.h"

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FBB10
#define VS_PARTICLE_TARGET_FUNCTION func_800FC298
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC4B0
#define VS_PARTICLE_RENDER_FUNCTION func_800FC960
#define VS_PARTICLE_CORNER_STATE D_800FDC58
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

#define VS_PARTICLE_RENDER_FUNCTION func_800FC960
#include "src/EFFECT/particleLineRender.h"
#undef VS_PARTICLE_RENDER_FUNCTION

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FBB10
#define VS_PARTICLE_TARGET_FUNCTION func_800FC298
#define VS_PARTICLE_CONTROL_FUNCTION func_800FC4B0
#define VS_PARTICLE_RENDER_FUNCTION func_800FC960
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FCE90
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"

INCLUDE_ASM("build/src/EFFECT/PLG168.BIN/nonmatchings/1F0", func_800FD104);
