sha1: 4efd158075021889666e4bb5f166416056d6b092
options:
  basename: EFFECT/PLG166.BIN
  target_path: data/EFFECT/PLG166.BIN
  elf_path: build/data/EFFECT/PLG166.BIN.elf
  asm_path: build/src/EFFECT/PLG166.BIN
  src_path: src/EFFECT/PLG166.BIN
  asset_path: build/assets/EFFECT/PLG166.BIN
  ld_script_path: build/config/EFFECT/PLG166.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG166.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG166.BIN/undefined_syms_auto.txt


segments:
  - name: PLG166.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0x36C0, data, 0]
  - [0x3980]
