sha1: 9ef5d7bd7bf19cd65ca0c9bd6dfbc56bfabeaf34
options:
  basename: EFFECT/PLG142.BIN
  target_path: data/EFFECT/PLG142.BIN
  elf_path: build/data/EFFECT/PLG142.BIN.elf
  asm_path: build/src/EFFECT/PLG142.BIN
  src_path: src/EFFECT/PLG142.BIN
  asset_path: build/assets/EFFECT/PLG142.BIN
  ld_script_path: build/config/EFFECT/PLG142.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG142.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG142.BIN/undefined_syms_auto.txt


segments:
  - name: PLG142.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 18]
    - [0x18, c]
    - [0x35B8, data, 18]
  - [0x35F8]
