$(BUILD)/data/MENU/MENU9.PRG.elf: LDSCRIPT += \
	config/SLUS_010.40/exports.txt \
	config/MENU/MAINMENU.PRG/exports.txt
$(BUILD)/src/MENU/MENU9.PRG/%.o: ASFLAGS += -no-pad-sections
$(BUILD)/src/MENU/MENU9.PRG/238.o: CC1VER := 2.8.0-psx
$(BUILD)/src/MENU/MENU9.PRG/4E00.o: CC1VER := 2.7.2-psx
