sha1: 92e3262a9ab4eb7afb81bbc64fd1e9bae7181231
options:
  basename: EFFECT/PLG143.BIN
  target_path: data/EFFECT/PLG143.BIN
  elf_path: build/data/EFFECT/PLG143.BIN.elf
  asm_path: build/src/EFFECT/PLG143.BIN
  src_path: src/EFFECT/PLG143.BIN
  asset_path: build/assets/EFFECT/PLG143.BIN
  ld_script_path: build/config/EFFECT/PLG143.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG143.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG143.BIN/undefined_syms_auto.txt


segments:
  - name: PLG143.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0x1E64, data, 0]
  - [0x1EA4]
