sha1: ebef5b166d6510efa6b6fd097827d4ab93acb4fc
options:
  basename: EFFECT/PLG149.BIN
  target_path: data/EFFECT/PLG149.BIN
  elf_path: build/data/EFFECT/PLG149.BIN.elf
  asm_path: build/src/EFFECT/PLG149.BIN
  src_path: src/EFFECT/PLG149.BIN
  asset_path: build/assets/EFFECT/PLG149.BIN
  ld_script_path: build/config/EFFECT/PLG149.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG149.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG149.BIN/undefined_syms_auto.txt


segments:
  - name: PLG149.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0xC24, data, 0]
  - [0xC44]
