#include "common.h"

INCLUDE_ASM("build/src/EFFECT/PLG146.BIN/nonmatchings/1D8", func_800F99D8);

INCLUDE_ASM("build/src/EFFECT/PLG146.BIN/nonmatchings/1D8", func_800FA8D0);

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FB544
#define VS_PARTICLE_TARGET_FUNCTION func_800FBCCC
#define VS_PARTICLE_CONTROL_FUNCTION func_800FBEE4
#define VS_PARTICLE_RENDER_FUNCTION func_800FC394
#define VS_PARTICLE_CORNER_STATE D_800FFB1C
#include "src/EFFECT/particleSetup.h"
#undef VS_PARTICLE_ORIGIN_FUNCTION
#undef VS_PARTICLE_TARGET_FUNCTION
#undef VS_PARTICLE_CONTROL_FUNCTION
#undef VS_PARTICLE_RENDER_FUNCTION
#undef VS_PARTICLE_CORNER_STATE

INCLUDE_ASM("build/src/EFFECT/PLG146.BIN/nonmatchings/1D8", func_800FC394);

#define VS_PARTICLE_ORIGIN_FUNCTION func_800FB544
#define VS_PARTICLE_TARGET_FUNCTION func_800FBCCC
#define VS_PARTICLE_CONTROL_FUNCTION func_800FBEE4
#define VS_PARTICLE_RENDER_FUNCTION func_800FC394
#define VS_PARTICLE_DISPATCH_FUNCTION func_800FC8C4
#define VS_PARTICLE_UNTEXTURED
#include "src/EFFECT/particleDispatch.h"

INCLUDE_ASM("build/src/EFFECT/PLG146.BIN/nonmatchings/1D8", func_800FCB38);

#define VS_TRAIL_ORIGIN_FUNCTION func_800FD75C
#define VS_TRAIL_TARGET_FUNCTION func_800FDEF8
#define VS_TRAIL_CONTROL_FUNCTION func_800FE110
#define VS_TRAIL_INIT_FUNCTION func_800FE5D4
#define VS_TRAIL_UPDATE_FUNCTION func_800FE74C
#define VS_TRAIL_RENDER_FUNCTION func_800FE8D8
#define VS_TRAIL_DISPATCH_FUNCTION func_800FF334
#define VS_TRAIL_CORNER_STATE D_800FFB40
#include "src/EFFECT/trails5.h"
