sha1: 509f8c82fe5d2751ca7736ea2d252050d9597327
options:
  basename: EFFECT/PLG156.BIN
  target_path: data/EFFECT/PLG156.BIN
  elf_path: build/data/EFFECT/PLG156.BIN.elf
  asm_path: build/src/EFFECT/PLG156.BIN
  src_path: src/EFFECT/PLG156.BIN
  asset_path: build/assets/EFFECT/PLG156.BIN
  ld_script_path: build/config/EFFECT/PLG156.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG156.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG156.BIN/undefined_syms_auto.txt


segments:
  - name: PLG156.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, 128]
    - [0x128, c]
    - [0x291C, data, 128]
  - [0x2920]
