sha1: 3cefac9bdd50602df737aaccb3b40f23ea807f22
options:
  basename: EFFECT/PLG160.BIN
  target_path: data/EFFECT/PLG160.BIN
  elf_path: build/data/EFFECT/PLG160.BIN.elf
  asm_path: build/src/EFFECT/PLG160.BIN
  src_path: src/EFFECT/PLG160.BIN
  asset_path: build/assets/EFFECT/PLG160.BIN
  ld_script_path: build/config/EFFECT/PLG160.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG160.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG160.BIN/undefined_syms_auto.txt


segments:
  - name: PLG160.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, c]
    - [0x1B1C, data, 0]
  - [0x1B5C]
