sha1: 1ffe5a242d5d1f51bc39b6d122ade5b52b7a08b4
options:
  basename: EFFECT/PLG050.BIN
  target_path: data/EFFECT/PLG050.BIN
  elf_path: build/data/EFFECT/PLG050.BIN.elf
  asm_path: build/src/EFFECT/PLG050.BIN
  src_path: src/EFFECT/PLG050.BIN
  asset_path: build/assets/EFFECT/PLG050.BIN
  ld_script_path: build/config/EFFECT/PLG050.BIN/link.ld
  symbol_addrs_path:
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/PLG050.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/PLG050.BIN/undefined_syms_auto.txt


segments:
  - name: PLG050.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0, .rodata, E0]
    - [0xE0, c]
    - [0x2E24, data, E0]
  - [0x2E48]
