#include "lbas.h"
#include "lbaMacros.h"

int _gimLbas[] = { squashLba(VS_STAFF011_GIM), squashLba(VS_STAFF001_GIM),
    squashLba(VS_STAFF002_GIM), squashLba(VS_STAFF003_GIM), squashLba(VS_STAFF004_GIM),
    squashLba(VS_STAFF005_GIM), squashLba(VS_STAFF006_GIM), squashLba(VS_STAFF007_GIM),
    squashLba(VS_STAFF008_GIM), squashLba(VS_GAMEOVER_GIM), squashLba(VS_STAFF009_GIM),
    squashLba(VS_STAFF010_GIM), squashLba(VS_STAFF012_GIM), squashLba(VS_ENKEI_GIM),
    squashLba(VS_LOGO_G22_GIM), squashLba(VS_STAFF013_GIM), squashLba(VS_1142_GIM),
    squashLba(VS_N_LEA_GIM), squashLba(VS_LOGO_28_GIM), squashLba(VS_LOGO_29_GIM),
    squashLba(VS_LOGO_30_GIM), squashLba(VS_LOGO_31_GIM), squashLba(VS_VKP_2_GIM),
    squashLba(VS_VKP_1_GIM), squashLba(VS_VKP_0_GIM), squashLba(VS_JYO_GIM),
    squashLba(VS_HEADQUAT_GIM), squashLba(VS_DEMOENK_GIM), squashLba(VS_DADDY_GIM),
    squashLba(VS_BLACK_GIM), squashLba(VS_ENKEI2_GIM), squashLba(VS_JO_GIM),
    squashLba(VS_SUNRISE_GIM), squashLba(VS_MAIN03_GIM), squashLba(VS_EPI_INF_GIM),
    squashLba(VS_EPILOGUE_GIM), squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM),
    squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM),
    squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM),
    squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM),
    squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM), squashLba(VS_STAFF013_GIM),
    squashLba(VS_STAFF013_GIM), squashLba(VS_EPI_E01B_GIM), squashLba(VS_EV_MASK_GIM),
    squashLba(VS_019XXX01_GIM), squashLba(VS_DEMO_001_GIM), squashLba(VS_DEMO_002_GIM),
    squashLba(VS_DEMO_003_GIM), squashLba(VS_DEMO_004_GIM), squashLba(VS_DEMO_005_GIM),
    squashLba(VS_DEMO_006_GIM), squashLba(VS_DEMO_007_GIM), squashLba(VS_DEMO_008_GIM),
    squashLba(VS_SQUARE_GIM), squashLba(VS_DEMOFIN_GIM) };