#include "lbas.h"

int _menuLbas[] = {
    VS_MAINMENU_PRG_LBA << 8 | (VS_MAINMENU_PRG_SIZE >> 11) + 12, // Wat
    VS_MENU0_PRG_LBA << 8 | VS_MENU0_PRG_SIZE >> 11,
    VS_MENU1_PRG_LBA << 8 | VS_MENU1_PRG_SIZE >> 11,
    VS_MENU2_PRG_LBA << 8 | VS_MENU2_PRG_SIZE >> 11,
    VS_MENU3_PRG_LBA << 8 | VS_MENU3_PRG_SIZE >> 11,
    VS_MENU4_PRG_LBA << 8 | VS_MENU4_PRG_SIZE >> 11,
    VS_MENU5_PRG_LBA << 8 | VS_MENU5_PRG_SIZE >> 11,
    VS_MENU7_PRG_LBA << 8 | VS_MENU7_PRG_SIZE >> 11,
    VS_MENU8_PRG_LBA << 8 | VS_MENU8_PRG_SIZE >> 11,
    VS_MENU9_PRG_LBA << 8 | VS_MENU9_PRG_SIZE >> 11,
    VS_MENUE_PRG_LBA << 8 | VS_MENUE_PRG_SIZE >> 11,
    VS_MENUA_PRG_LBA << 8 | VS_MENUA_PRG_SIZE >> 11,
    VS_MENUB_PRG_LBA << 8 | VS_MENUB_PRG_SIZE >> 11,
    VS_MENUC_PRG_LBA << 8 | VS_MENUC_PRG_SIZE >> 11,
    VS_MENUD_PRG_LBA << 8 | VS_MENUD_PRG_SIZE >> 11,
    VS_MENUF_PRG_LBA << 8 | VS_MENUF_PRG_SIZE >> 11,
};