name: Format

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: format-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check formatting
        run: |
          make format -j8
          git diff --exit-code
