sha1: 670a22661d68bc700c3d52125f38a0ec42daeb1c
options:
  basename: EFFECT/EFFPURGE.BIN
  target_path: data/EFFECT/EFFPURGE.BIN
  elf_path: build/data/EFFECT/EFFPURGE.BIN.elf
  asm_path: build/src/EFFECT/EFFPURGE.BIN
  src_path: src/EFFECT/EFFPURGE.BIN
  asset_path: build/assets/EFFECT/EFFPURGE.BIN
  ld_script_path: build/config/EFFECT/EFFPURGE.BIN/link.ld
  symbol_addrs_path:
    - config/EFFECT/EFFPURGE.BIN/symbol_addrs.txt
    - config/SLUS_010.40/symbol_addrs.txt
    - config/BATTLE/BATTLE.PRG/symbol_addrs.txt
  undefined_funcs_auto_path: build/config/EFFECT/EFFPURGE.BIN/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/config/EFFECT/EFFPURGE.BIN/undefined_syms_auto.txt


segments:
  - name: EFFPURGE.BIN
    start: 0x0
    type: code
    vram: 0x800F9800
    align: 4
    subsegments:
    - [0x0, c]
    - [0x164C, data]
  - [0x4370]
